env:
  browser: true
  es2020: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'airbnb-base'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
settings:
  react:
    version: detect
ignorePatterns:
  - /public/*.js
rules:
  consistent-return:
    - off
  no-console:
    - off
  array-callback-return:
    - off
  no-underscore-dangle:
    - off
